services:
  - type: web
    name: thinkify-backend
    env: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start

  - type: static
    name: thinkify-frontend
    env: static
    plan: free
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
